import { fixupPluginRules } from "@eslint/compat";
import { ignores, languageOptions } from "./constants.js";
import a11y from "eslint-plugin-jsx-a11y";
import barrel from "eslint-plugin-barrel-files";
import compat from "eslint-plugin-compat";
import cspell from "@cspell/eslint-plugin";
import depend from "eslint-plugin-depend";
import json from "@eslint/json";
import lodashConfig from "eslint-plugin-lodash";
import markdown from "@eslint/markdown";
import n from "eslint-plugin-n";
import perfectionist from "eslint-plugin-perfectionist";
import sonar from "eslint-plugin-sonarjs";
import stylistic from "@stylistic/eslint-plugin";
import stylisticTs from "@stylistic/eslint-plugin-ts";
import tailwind from "eslint-plugin-tailwindcss";
import tanstackQuery from "@tanstack/eslint-plugin-query";
import tanstackRouter from "@tanstack/eslint-plugin-router";
import tseslint from "typescript-eslint";
import unicorn from "eslint-plugin-unicorn";

export default tseslint.config(
  {
    files: ["**/*.{js,ts,jsx,tsx,cjs,cts,mjs,mts}"],
    ignores,
    languageOptions,
    settings: {
      react: { version: "18.3.1" },
    },
    plugins: {
      depend: depend,
      cspell: cspell,
      barrel: barrel,
      compat: compat,
      n: n,
      "@typescript-eslint": tseslint.plugin,
      unicorn: unicorn,
      lodash: lodashConfig,
      sonar: fixupPluginRules(sonar),
      tailwind: tailwind,
      stylistic: stylistic,
      "stylistic-ts": stylisticTs,
      perfectionist: perfectionist,
      "@tanstack/query": tanstackQuery,
      "@tanstack/router": tanstackRouter,
      a11y: a11y,
    },
    rules: {
      "depend/ban-dependencies": ["error", { allowed: ["lodash", "fs-extra"] }],
      "cspell/spellchecker": [
        "error",
        {
          cspell: {
            words: [
              "toolbelt",
              "taze",
              "ethang",
              "TSESTree",
              "Boop",
              "cldr",
              "astro",
              "laravel",
              "qwik",
              "sitecore",
              "uswds",
              "mediat",
              "Packt",
              "Academind",
              "Udemy",
              "Colte",
              "Bootcamp",
              "HTMX",
              "MERN",
              "Nuxt",
              "Credly",
              "Sterett",
              "Beyonder",
              "hotspot",
              "lqip",
              "Hawn",
              "nextui",
              "speculationrules",
              "zustand",
              "vinxi",
              "datasource",
              "turso",
              "supabase",
              "solidjs",
            ],
          },
        },
      ],
      "barrel/avoid-barrel-files": "error",
      "barrel/avoid-importing-barrel-files": "error",
      "barrel/avoid-namespace-import": "error",
      "barrel/avoid-re-export-all": "error",
      "compat/compat": "error",
      "accessor-pairs": "error",
      "array-callback-return": "error",
      "arrow-body-style": ["error", "always"],
      "block-scoped-var": "error",
      camelcase: "off",
      "capitalized-comments": "off",
      "class-methods-use-this": "off",
      complexity: "off",
      "consistent-return": "off",
      "consistent-this": "off",
      "constructor-super": "error",
      curly: "off",
      "default-case": "off",
      "default-case-last": "off",
      "default-param-last": "off",
      "dot-notation": "off",
      eqeqeq: "error",
      "for-direction": "error",
      "func-name-matching": "error",
      "func-names": "off",
      "func-style": ["error", "declaration", { allowArrowFunctions: true }],
      "getter-return": "error",
      "grouped-accessor-pairs": "error",
      "guard-for-in": "error",
      "id-denylist": "off",
      "id-length": "off",
      "id-match": "off",
      "init-declarations": "off",
      "logical-assignment-operators": "error",
      "max-classes-per-file": "error",
      "max-depth": "error",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "error",
      "max-params": "off",
      "max-statements": "error",
      "new-cap": "off",
      "no-alert": "error",
      "no-array-constructor": "off",
      "no-async-promise-executor": "error",
      "no-await-in-loop": "error",
      "no-bitwise": "error",
      "no-caller": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-console": "error",
      "no-const-assign": "error",
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-constructor-return": "error",
      "no-continue": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-div-regex": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "off",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-duplicate-imports": "error",
      "no-else-return": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-function": "off",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-eq-null": "error",
      "no-eval": "error",
      "no-ex-assign": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-extra-boolean-cast": "error",
      "no-extra-label": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-implicit-coercion": "error",
      "no-implicit-globals": "off",
      "no-implied-eval": "off",
      "no-import-assign": "error",
      "no-inline-comments": "off",
      "no-inner-declarations": "error",
      "no-invalid-regexp": "error",
      "no-invalid-this": "error",
      "no-irregular-whitespace": "error",
      "no-iterator": "error",
      "no-label-var": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-lonely-if": "error",
      "no-loop-func": "error",
      "no-loss-of-precision": "error",
      "no-magic-numbers": "off",
      "no-misleading-character-class": "error",
      "no-multi-assign": "error",
      "no-multi-str": "error",
      "no-negated-condition": "error",
      "no-nested-ternary": "error",
      "no-new": "error",
      "no-new-func": "error",
      "no-new-native-nonconstructor": "error",
      "no-new-wrappers": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-object-constructor": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-param-reassign": "error",
      "no-plusplus": "error",
      "no-promise-executor-return": "error",
      "no-proto": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "off",
      "no-regex-spaces": "error",
      "no-restricted-exports": "off",
      "no-restricted-globals": "off",
      "no-restricted-imports": "off",
      "no-restricted-properties": "off",
      "no-restricted-syntax": "off",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-setter-return": "error",
      "no-shadow": "off",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-template-curly-in-string": "off",
      "no-ternary": "off",
      "no-this-before-super": "error",
      "no-throw-literal": "off",
      "no-undef": "off",
      "no-undef-init": "error",
      "no-undefined": "off",
      "no-underscore-dangle": "off",
      "no-unexpected-multiline": "off",
      "no-unmodified-loop-condition": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable": "error",
      "no-unreachable-loop": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": [
        "error",
        { disallowArithmeticOperators: true },
      ],
      "no-unused-expressions": "off",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": "off",
      "no-use-before-define": "off",
      "no-useless-assignment": "off",
      "no-useless-backreference": "error",
      "no-useless-call": "error",
      "no-useless-catch": "error",
      "no-useless-computed-key": "error",
      "no-useless-concat": "error",
      "no-useless-constructor": "off",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-var": "error",
      "no-void": "error",
      "no-warning-comments": "off",
      "no-with": "error",
      "object-shorthand": "error",
      "one-var": "off",
      "operator-assignment": "error",
      "prefer-arrow-callback": "error",
      "prefer-const": "error",
      "prefer-destructuring": "off",
      "prefer-exponentiation-operator": "error",
      "prefer-named-capture-group": "error",
      "prefer-numeric-literals": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-promise-reject-errors": "off",
      "prefer-regex-literals": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "error",
      radix: "error",
      "require-atomic-updates": "error",
      "require-await": "off",
      "require-unicode-regexp": "error",
      "require-yield": "error",
      "sort-imports": "off",
      "sort-keys": "off",
      "sort-vars": "error",
      strict: "error",
      "symbol-description": "error",
      "unicode-bom": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "vars-on-top": "error",
      yoda: ["error", "always"],
      "n/callback-return": "off",
      "n/exports-style": ["error", "exports"],
      "n/file-extension-in-import": "off",
      "n/global-require": "off",
      "n/handle-callback-err": "error",
      "n/hashbang": "off",
      "n/no-callback-literal": "off",
      "n/no-deprecated-api": "error",
      "n/no-exports-assign": "error",
      "n/no-extraneous-import": "error",
      "n/no-extraneous-require": "error",
      "n/no-missing-import": "off",
      "n/no-missing-require": "error",
      "n/no-mixed-requires": "off",
      "n/no-new-require": "off",
      "n/no-path-concat": "error",
      "n/no-process-env": "off",
      "n/no-process-exit": "off",
      "n/no-restricted-import": "off",
      "n/no-restricted-require": "off",
      "n/no-sync": "off",
      "n/no-unpublished-bin": "error",
      "n/no-unpublished-import": "off",
      "n/no-unpublished-require": "off",
      "n/no-unsupported-features/es-builtins": "error",
      "n/no-unsupported-features/es-syntax": "error",
      "n/no-unsupported-features/node-builtins": "error",
      "n/prefer-global/buffer": "error",
      "n/prefer-global/console": "error",
      "n/prefer-global/process": "error",
      "n/prefer-global/text-decoder": "error",
      "n/prefer-global/text-encoder": "error",
      "n/prefer-global/url": "error",
      "n/prefer-global/url-search-params": "error",
      "n/prefer-node-protocol": "error",
      "n/prefer-promises/dns": "off",
      "n/prefer-promises/fs": "off",
      "n/process-exit-as-throw": "off",
      "@typescript-eslint/adjacent-overload-signatures": "off",
      "@typescript-eslint/array-type": "error",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/ban-ts-comment": "error",
      "@typescript-eslint/ban-tslint-comment": "error",
      "@typescript-eslint/class-literal-property-style": "error",
      "@typescript-eslint/class-methods-use-this": "off",
      "@typescript-eslint/consistent-generic-constructors": "error",
      "@typescript-eslint/consistent-indexed-object-style": "error",
      "@typescript-eslint/consistent-return": "off",
      "@typescript-eslint/consistent-type-assertions": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "type"],
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/default-param-last": "error",
      "@typescript-eslint/dot-notation": "error",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-member-accessibility": "error",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/init-declarations": "off",
      "@typescript-eslint/max-params": "off",
      "@typescript-eslint/member-ordering": "off",
      "@typescript-eslint/method-signature-style": "error",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-array-constructor": "error",
      "@typescript-eslint/no-array-delete": "error",
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/no-confusing-non-null-assertion": "error",
      "@typescript-eslint/no-confusing-void-expression": "error",
      "@typescript-eslint/no-deprecated": "error",
      "@typescript-eslint/no-dupe-class-members": "off",
      "@typescript-eslint/no-duplicate-enum-values": "error",
      "@typescript-eslint/no-duplicate-type-constituents": "error",
      "@typescript-eslint/no-dynamic-delete": "error",
      "@typescript-eslint/no-empty-function": "error",
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-extraneous-class": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-for-in-array": "error",
      "@typescript-eslint/no-implied-eval": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/no-inferrable-types": "error",
      "@typescript-eslint/no-invalid-this": "off",
      "@typescript-eslint/no-invalid-void-type": "error",
      "@typescript-eslint/no-loop-func": "error",
      "@typescript-eslint/no-magic-numbers": "off",
      "@typescript-eslint/no-meaningless-void-operator": "error",
      "@typescript-eslint/no-misused-new": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-mixed-enums": "error",
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-redeclare": "off",
      "@typescript-eslint/no-redundant-type-constituents": "error",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-restricted-imports": "error",
      "@typescript-eslint/no-restricted-types": "error",
      "@typescript-eslint/no-shadow": "error",
      "@typescript-eslint/no-this-alias": "error",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
      "@typescript-eslint/no-unnecessary-condition": "error",
      "@typescript-eslint/no-unnecessary-parameter-property-assignment":
        "error",
      "@typescript-eslint/no-unnecessary-qualifier": "error",
      "@typescript-eslint/no-unnecessary-template-expression": "error",
      "@typescript-eslint/no-unnecessary-type-arguments": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/no-unnecessary-type-constraint": "error",
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-declaration-merging": "error",
      "@typescript-eslint/no-unsafe-enum-comparison": "error",
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-unary-minus": "error",
      "@typescript-eslint/no-unused-expressions": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          args: "all",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
          ignoreRestSiblings: true,
          varsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-use-before-define": "off",
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/no-useless-empty-export": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      "@typescript-eslint/non-nullable-type-assertion-style": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/parameter-properties": "off",
      "@typescript-eslint/prefer-as-const": "error",
      "@typescript-eslint/prefer-destructuring": "error",
      "@typescript-eslint/prefer-enum-initializers": "error",
      "@typescript-eslint/prefer-find": "error",
      "@typescript-eslint/prefer-for-of": "error",
      "@typescript-eslint/prefer-function-type": "error",
      "@typescript-eslint/prefer-includes": "error",
      "@typescript-eslint/prefer-literal-enum-member": "error",
      "@typescript-eslint/prefer-namespace-keyword": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/prefer-promise-reject-errors": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-readonly-parameter-types": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/prefer-regexp-exec": "error",
      "@typescript-eslint/prefer-return-this-type": "error",
      "@typescript-eslint/prefer-string-starts-ends-with": "error",
      "@typescript-eslint/promise-function-async": "error",
      "@typescript-eslint/require-array-sort-compare": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/restrict-plus-operands": "error",
      "@typescript-eslint/restrict-template-expressions": "error",
      "@typescript-eslint/return-await": "error",
      "@typescript-eslint/strict-boolean-expressions": "error",
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/triple-slash-reference": "error",
      "@typescript-eslint/typedef": "off",
      "@typescript-eslint/unbound-method": "error",
      "@typescript-eslint/unified-signatures": "error",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
      "unicorn/better-regex": "error",
      "unicorn/catch-error-name": "error",
      "unicorn/consistent-destructuring": "error",
      "unicorn/consistent-empty-array-spread": "error",
      "unicorn/consistent-existence-index-check": "error",
      "unicorn/consistent-function-scoping": "error",
      "unicorn/custom-error-definition": "error",
      "unicorn/empty-brace-spaces": "off",
      "unicorn/error-message": "error",
      "unicorn/escape-case": "error",
      "unicorn/expiring-todo-comments": "error",
      "unicorn/explicit-length-check": "off",
      "unicorn/filename-case": "error",
      "unicorn/import-style": "error",
      "unicorn/new-for-builtins": "error",
      "unicorn/no-abusive-eslint-disable": "error",
      "unicorn/no-anonymous-default-export": "error",
      "unicorn/no-array-callback-reference": "error",
      "unicorn/no-array-for-each": "error",
      "unicorn/no-array-method-this-argument": "error",
      "unicorn/no-array-push-push": "error",
      "unicorn/no-array-reduce": "error",
      "unicorn/no-await-expression-member": "error",
      "unicorn/no-await-in-promise-methods": "error",
      "unicorn/no-console-spaces": "error",
      "unicorn/no-document-cookie": "error",
      "unicorn/no-empty-file": "error",
      "unicorn/no-for-loop": "error",
      "unicorn/no-hex-escape": "error",
      "unicorn/no-instanceof-array": "error",
      "unicorn/no-invalid-fetch-options": "error",
      "unicorn/no-invalid-remove-event-listener": "error",
      "unicorn/no-keyword-prefix": "off",
      "unicorn/no-length-as-slice-end": "error",
      "unicorn/no-lonely-if": "error",
      "unicorn/no-magic-array-flat-depth": "error",
      "unicorn/no-negated-condition": "error",
      "unicorn/no-negation-in-equality-check": "error",
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-new-array": "error",
      "unicorn/no-new-buffer": "error",
      "unicorn/no-null": "off",
      "unicorn/no-object-as-default-parameter": "error",
      "unicorn/no-process-exit": "error",
      "unicorn/no-single-promise-in-promise-methods": "error",
      "unicorn/no-static-only-class": "error",
      "unicorn/no-thenable": "error",
      "unicorn/no-this-assignment": "error",
      "unicorn/no-typeof-undefined": "error",
      "unicorn/no-unnecessary-await": "error",
      "unicorn/no-unnecessary-polyfills": "error",
      "unicorn/no-unreadable-array-destructuring": "error",
      "unicorn/no-unreadable-iife": "error",
      "unicorn/no-unused-properties": "error",
      "unicorn/no-useless-fallback-in-spread": "error",
      "unicorn/no-useless-length-check": "error",
      "unicorn/no-useless-promise-resolve-reject": "error",
      "unicorn/no-useless-spread": "error",
      "unicorn/no-useless-switch-case": "error",
      "unicorn/no-useless-undefined": "error",
      "unicorn/no-zero-fractions": "error",
      "unicorn/number-literal-case": "off",
      "unicorn/numeric-separators-style": "error",
      "unicorn/prefer-add-event-listener": "error",
      "unicorn/prefer-array-find": "error",
      "unicorn/prefer-array-flat": "error",
      "unicorn/prefer-array-flat-map": "error",
      "unicorn/prefer-array-index-of": "error",
      "unicorn/prefer-array-some": "error",
      "unicorn/prefer-at": "error",
      "unicorn/prefer-blob-reading-methods": "error",
      "unicorn/prefer-code-point": "error",
      "unicorn/prefer-date-now": "error",
      "unicorn/prefer-default-parameters": "error",
      "unicorn/prefer-dom-node-append": "error",
      "unicorn/prefer-dom-node-dataset": "error",
      "unicorn/prefer-dom-node-remove": "error",
      "unicorn/prefer-dom-node-text-content": "error",
      "unicorn/prefer-event-target": "error",
      "unicorn/prefer-export-from": "error",
      "unicorn/prefer-global-this": "error",
      "unicorn/prefer-includes": "error",
      "unicorn/prefer-json-parse-buffer": "error",
      "unicorn/prefer-keyboard-event-key": "error",
      "unicorn/prefer-logical-operator-over-ternary": "error",
      "unicorn/prefer-math-min-max": "error",
      "unicorn/prefer-math-trunc": "error",
      "unicorn/prefer-modern-dom-apis": "error",
      "unicorn/prefer-modern-math-apis": "error",
      "unicorn/prefer-module": "error",
      "unicorn/prefer-native-coercion-functions": "error",
      "unicorn/prefer-negative-index": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/prefer-number-properties": "error",
      "unicorn/prefer-object-from-entries": "error",
      "unicorn/prefer-optional-catch-binding": "error",
      "unicorn/prefer-prototype-methods": "error",
      "unicorn/prefer-query-selector": "error",
      "unicorn/prefer-reflect-apply": "error",
      "unicorn/prefer-regexp-test": "error",
      "unicorn/prefer-set-has": "error",
      "unicorn/prefer-set-size": "error",
      "unicorn/prefer-spread": "error",
      "unicorn/prefer-string-raw": "error",
      "unicorn/prefer-string-replace-all": "error",
      "unicorn/prefer-string-slice": "error",
      "unicorn/prefer-string-starts-ends-with": "error",
      "unicorn/prefer-string-trim-start-end": "error",
      "unicorn/prefer-structured-clone": "error",
      "unicorn/prefer-switch": "error",
      "unicorn/prefer-ternary": "error",
      "unicorn/prefer-top-level-await": "error",
      "unicorn/prefer-type-error": "error",
      "unicorn/prevent-abbreviations": "error",
      "unicorn/relative-url-style": "error",
      "unicorn/require-array-join-separator": "error",
      "unicorn/require-number-to-fixed-digits-argument": "error",
      "unicorn/require-post-message-target-origin": "error",
      "unicorn/string-content": "error",
      "unicorn/switch-case-braces": "error",
      "unicorn/template-indent": "off",
      "unicorn/text-encoding-identifier-case": "error",
      "unicorn/throw-new-error": "error",
      "lodash/callback-binding": "error",
      "lodash/chain-style": [2, "as-needed"],
      "lodash/chaining": "error",
      "lodash/collection-method-value": "error",
      "lodash/collection-ordering": "error",
      "lodash/collection-return": "error",
      "lodash/consistent-compose": [2, "flow"],
      "lodash/identity-shorthand": [2, "always"],
      "lodash/import-scope": [2, "method"],
      "lodash/matches-prop-shorthand": [2, "always"],
      "lodash/matches-shorthand": [2, "always", 3],
      "lodash/no-commit": "error",
      "lodash/no-double-unwrap": "error",
      "lodash/no-extra-args": "error",
      "lodash/no-unbound-this": "error",
      "lodash/path-style": [2, "array"],
      "lodash/prefer-compact": "error",
      "lodash/prefer-constant": "error",
      "lodash/prefer-filter": "error",
      "lodash/prefer-find": "error",
      "lodash/prefer-flat-map": "error",
      "lodash/prefer-get": "error",
      "lodash/prefer-immutable-method": "error",
      "lodash/prefer-includes": [2, { includeNative: true }],
      "lodash/prefer-invoke-map": "error",
      "lodash/prefer-is-nil": "error",
      "lodash/prefer-lodash-chain": "error",
      "lodash/prefer-lodash-method": "error",
      "lodash/prefer-lodash-typecheck": "error",
      "lodash/prefer-map": "error",
      "lodash/prefer-matches": "error",
      "lodash/prefer-noop": "error",
      "lodash/prefer-over-quantifier": "error",
      "lodash/prefer-reject": "error",
      "lodash/prefer-some": [2, { includeNative: true }],
      "lodash/prefer-startswith": "error",
      "lodash/prefer-thru": "error",
      "lodash/prefer-times": "error",
      "lodash/prefer-wrapper-method": "error",
      "lodash/preferred-alias": "error",
      "lodash/prop-shorthand": [2, "always"],
      "lodash/unwrap": "error",
      "sonar/accessor-pairs": "error",
      "sonar/alt-text": "error",
      "sonar/anchor-has-content": "error",
      "sonar/anchor-is-valid": "error",
      "sonar/anchor-precedence": "error",
      "sonar/argument-type": "error",
      "sonar/arguments-order": "error",
      "sonar/arguments-usage": "error",
      "sonar/array-callback-without-return": "error",
      "sonar/array-constructor": "error",
      "sonar/arrow-function-convention": "off",
      "sonar/assertions-in-tests": "error",
      "sonar/aws-apigateway-public-api": "error",
      "sonar/aws-ec2-rds-dms-public": "error",
      "sonar/aws-ec2-unencrypted-ebs-volume": "error",
      "sonar/aws-efs-unencrypted": "error",
      "sonar/aws-iam-all-privileges": "error",
      "sonar/aws-iam-all-resources-accessible": "error",
      "sonar/aws-iam-privilege-escalation": "error",
      "sonar/aws-iam-public-access": "error",
      "sonar/aws-opensearchservice-domain": "error",
      "sonar/aws-rds-unencrypted-databases": "error",
      "sonar/aws-restricted-ip-admin-access": "error",
      "sonar/aws-s3-bucket-granted-access": "error",
      "sonar/aws-s3-bucket-insecure-http": "error",
      "sonar/aws-s3-bucket-public-access": "error",
      "sonar/aws-s3-bucket-versioning": "error",
      "sonar/aws-sagemaker-unencrypted-notebook": "error",
      "sonar/aws-sns-unencrypted-topics": "error",
      "sonar/aws-sqs-unencrypted-queue": "error",
      "sonar/bitwise-operators": "error",
      "sonar/bool-param-default": "error",
      "sonar/call-argument-line": "error",
      "sonar/certificate-transparency": "error",
      "sonar/chai-determinate-assertion": "error",
      "sonar/class-name": "error",
      "sonar/class-prototype": "error",
      "sonar/code-eval": "error",
      "sonar/cognitive-complexity": "error",
      "sonar/comma-or-logical-or-case": "error",
      "sonar/comment-regex": "off",
      "sonar/concise-regex": "error",
      "sonar/confidential-information-logging": "error",
      "sonar/constructor-for-side-effects": "error",
      "sonar/content-length": "error",
      "sonar/content-security-policy": "error",
      "sonar/cookie-no-httponly": "error",
      "sonar/cors": "error",
      "sonar/csrf": "error",
      "sonar/cyclomatic-complexity": "off",
      "sonar/declarations-in-global-scope": "error",
      "sonar/default-param-last": "error",
      "sonar/deprecation": "error",
      "sonar/destructuring-assignment-syntax": "error",
      "sonar/different-types-comparison": "error",
      "sonar/disabled-auto-escaping": "error",
      "sonar/disabled-resource-integrity": "error",
      "sonar/disabled-timeout": "error",
      "sonar/duplicates-in-character-class": "error",
      "sonar/elseif-without-else": "error",
      "sonar/empty-string-repetition": "error",
      "sonar/encryption-secure-mode": "error",
      "sonar/existing-groups": "error",
      "sonar/expression-complexity": "error",
      "sonar/file-header": "off",
      "sonar/file-name-differ-from-class": "error",
      "sonar/file-permissions": "error",
      "sonar/file-uploads": "error",
      "sonar/fixme-tag": "error",
      "sonar/for-in": "error",
      "sonar/for-loop-increment-sign": "error",
      "sonar/frame-ancestors": "error",
      "sonar/function-inside-loop": "error",
      "sonar/function-name": [
        "error",
        { format: "^(?:[a-z][a-zA-Z0-9]*|[A-Z][A-Z0-9]*)$" },
      ],
      "sonar/function-return-type": "off",
      "sonar/future-reserved-words": "error",
      "sonar/generator-without-yield": "error",
      "sonar/hashing": "error",
      "sonar/hidden-files": "error",
      "sonar/hook-use-state": "error",
      "sonar/html-has-lang": "error",
      "sonar/in-operator-type-error": "error",
      "sonar/inconsistent-function-call": "error",
      "sonar/index-of-compare-to-positive-number": "error",
      "sonar/insecure-cookie": "error",
      "sonar/insecure-jwt-token": "error",
      "sonar/inverted-assertion-arguments": "error",
      "sonar/jsx-key": "error",
      "sonar/jsx-no-constructed-context-values": "error",
      "sonar/jsx-no-useless-fragment": "error",
      "sonar/label-has-associated-control": "error",
      "sonar/label-position": "error",
      "sonar/link-with-target-blank": "error",
      "sonar/max-switch-cases": "error",
      "sonar/max-union-size": "off",
      "sonar/media-has-caption": "error",
      "sonar/misplaced-loop-counter": "error",
      "sonar/mouse-events-a11y": "error",
      "sonar/nested-control-flow": "error",
      "sonar/new-cap": "off",
      "sonar/new-operator-misuse": "error",
      "sonar/no-accessor-field-mismatch": "error",
      "sonar/no-all-duplicated-branches": "error",
      "sonar/no-alphabetical-sort": "error",
      "sonar/no-angular-bypass-sanitization": "error",
      "sonar/no-array-delete": "error",
      "sonar/no-array-index-key": "error",
      "sonar/no-associative-arrays": "error",
      "sonar/no-async-constructor": "error",
      "sonar/no-base-to-string": "error",
      "sonar/no-built-in-override": "error",
      "sonar/no-case-label-in-switch": "error",
      "sonar/no-clear-text-protocols": "error",
      "sonar/no-code-after-done": "error",
      "sonar/no-collapsible-if": "error",
      "sonar/no-collection-size-mischeck": "error",
      "sonar/no-commented-code": "error",
      "sonar/no-dead-store": "error",
      "sonar/no-delete-var": "error",
      "sonar/no-deprecated-react": "error",
      "sonar/no-duplicate-in-composite": "error",
      "sonar/no-duplicate-string": "error",
      "sonar/no-duplicated-branches": "error",
      "sonar/no-element-overwrite": "error",
      "sonar/no-empty-after-reluctant": "error",
      "sonar/no-empty-alternatives": "error",
      "sonar/no-empty-collection": "error",
      "sonar/no-empty-function": "error",
      "sonar/no-empty-group": "error",
      "sonar/no-empty-interface": "error",
      "sonar/no-empty-test-file": "error",
      "sonar/no-equals-in-for-termination": "error",
      "sonar/no-exclusive-tests": "error",
      "sonar/no-extend-native": "error",
      "sonar/no-extra-arguments": "error",
      "sonar/no-find-dom-node": "error",
      "sonar/no-for-in-iterable": "error",
      "sonar/no-function-declaration-in-block": "error",
      "sonar/no-global-this": "error",
      "sonar/no-globals-shadowing": "error",
      "sonar/no-gratuitous-expressions": "error",
      "sonar/no-hardcoded-credentials": "error",
      "sonar/no-hardcoded-ip": "error",
      "sonar/no-hook-setter-in-body": "error",
      "sonar/no-identical-conditions": "error",
      "sonar/no-identical-expressions": "error",
      "sonar/no-identical-functions": "error",
      "sonar/no-ignored-exceptions": "error",
      "sonar/no-ignored-return": "error",
      "sonar/no-implicit-dependencies": "off",
      "sonar/no-implicit-global": "error",
      "sonar/no-in-misuse": "error",
      "sonar/no-incomplete-assertions": "error",
      "sonar/no-inconsistent-returns": "off",
      "sonar/no-incorrect-string-concat": "error",
      "sonar/no-infinite-loop": "error",
      "sonar/no-internal-api-use": "error",
      "sonar/no-intrusive-permissions": "error",
      "sonar/no-invalid-await": "error",
      "sonar/no-invariant-returns": "error",
      "sonar/no-inverted-boolean-check": "error",
      "sonar/no-ip-forward": "error",
      "sonar/no-labels": "error",
      "sonar/no-literal-call": "error",
      "sonar/no-lonely-if": "error",
      "sonar/no-mime-sniff": "error",
      "sonar/no-misleading-array-reverse": "error",
      "sonar/no-misused-promises": "error",
      "sonar/no-mixed-content": "error",
      "sonar/no-nested-assignment": "error",
      "sonar/no-nested-conditional": "error",
      "sonar/no-nested-functions": "error",
      "sonar/no-nested-incdec": "error",
      "sonar/no-nested-switch": "error",
      "sonar/no-nested-template-literals": "error",
      "sonar/no-one-iteration-loop": "error",
      "sonar/no-os-command-from-path": "error",
      "sonar/no-parameter-reassignment": "error",
      "sonar/no-primitive-wrappers": "error",
      "sonar/no-redeclare": "error",
      "sonar/no-redundant-assignments": "error",
      "sonar/no-redundant-boolean": "error",
      "sonar/no-redundant-jump": "error",
      "sonar/no-redundant-optional": "error",
      "sonar/no-redundant-type-constituents": "error",
      "sonar/no-reference-error": "off",
      "sonar/no-referrer-policy": "error",
      "sonar/no-require-or-define": "error",
      "sonar/no-return-type-any": "error",
      "sonar/no-same-argument-assert": "error",
      "sonar/no-same-line-conditional": "error",
      "sonar/no-selector-parameter": "error",
      "sonar/no-self-compare": "error",
      "sonar/no-self-import": "error",
      "sonar/no-skipped-test": "error",
      "sonar/no-small-switch": "error",
      "sonar/no-table-as-layout": "error",
      "sonar/no-this-alias": "error",
      "sonar/no-throw-literal": "error",
      "sonar/no-try-promise": "error",
      "sonar/no-undefined-argument": "error",
      "sonar/no-undefined-assignment": "off",
      "sonar/no-unenclosed-multiline-block": "error",
      "sonar/no-uniq-key": "error",
      "sonar/no-unknown-property": "error",
      "sonar/no-unreachable": "error",
      "sonar/no-unsafe": "error",
      "sonar/no-unsafe-unzip": "error",
      "sonar/no-unstable-nested-components": "error",
      "sonar/no-unthrown-error": "error",
      "sonar/no-unused-collection": "error",
      "sonar/no-unused-expressions": "error",
      "sonar/no-unused-function-argument": "error",
      "sonar/no-unused-private-class-members": "error",
      "sonar/no-use-of-empty-return-value": "error",
      "sonar/no-useless-call": "error",
      "sonar/no-useless-catch": "error",
      "sonar/no-useless-constructor": "error",
      "sonar/no-useless-increment": "error",
      "sonar/no-useless-intersection": "error",
      "sonar/no-useless-react-setstate": "error",
      "sonar/no-var": "error",
      "sonar/no-variable-usage-before-declaration": "error",
      "sonar/no-vue-bypass-sanitization": "error",
      "sonar/no-weak-cipher": "error",
      "sonar/no-weak-keys": "error",
      "sonar/no-wildcard-import": "error",
      "sonar/non-existent-operator": "error",
      "sonar/non-number-in-arithmetic-expression": "error",
      "sonar/null-dereference": "error",
      "sonar/object-alt-content": "error",
      "sonar/object-shorthand": "error",
      "sonar/operation-returning-nan": "error",
      "sonar/os-command": "error",
      "sonar/post-message": "error",
      "sonar/prefer-default-last": "error",
      "sonar/prefer-enum-initializers": "error",
      "sonar/prefer-for-of": "error",
      "sonar/prefer-function-type": "error",
      "sonar/prefer-immediate-return": "error",
      "sonar/prefer-namespace-keyword": "error",
      "sonar/prefer-nullish-coalescing": "error",
      "sonar/prefer-object-literal": "error",
      "sonar/prefer-object-spread": "error",
      "sonar/prefer-promise-shorthand": "error",
      "sonar/prefer-single-boolean-return": "error",
      "sonar/prefer-spread": "error",
      "sonar/prefer-string-starts-ends-with": "error",
      "sonar/prefer-template": "error",
      "sonar/prefer-type-guard": "error",
      "sonar/prefer-while": "error",
      "sonar/production-debug": "error",
      "sonar/pseudo-random": "error",
      "sonar/public-static-readonly": "error",
      "sonar/publicly-writable-directories": "error",
      "sonar/reduce-initial-value": "error",
      "sonar/redundant-type-aliases": "error",
      "sonar/regex-complexity": "error",
      "sonar/rules-of-hooks": "error",
      "sonar/session-regeneration": "error",
      "sonar/shorthand-property-grouping": "off",
      "sonar/single-char-in-character-classes": "error",
      "sonar/single-character-alternation": "error",
      "sonar/slow-regex": "error",
      "sonar/sonar-block-scoped-var": "error",
      "sonar/sonar-jsx-no-leaked-render": "error",
      "sonar/sonar-max-lines": "error",
      "sonar/sonar-max-lines-per-function": "error",
      "sonar/sonar-max-params": "error",
      "sonar/sonar-no-control-regex": "error",
      "sonar/sonar-no-dupe-keys": "error",
      "sonar/sonar-no-empty-character-class": "error",
      "sonar/sonar-no-fallthrough": "off",
      "sonar/sonar-no-invalid-regexp": "error",
      "sonar/sonar-no-magic-numbers": "off",
      "sonar/sonar-no-misleading-character-class": "error",
      "sonar/sonar-no-regex-spaces": "error",
      "sonar/sonar-no-unused-class-component-methods": "error",
      "sonar/sonar-no-unused-vars": "error",
      "sonar/sonar-prefer-optional-chain": "error",
      "sonar/sonar-prefer-read-only-props": "error",
      "sonar/sonar-prefer-regexp-exec": "error",
      "sonar/sql-queries": "error",
      "sonar/stable-tests": "error",
      "sonar/stateful-regex": "error",
      "sonar/strict-transport-security": "error",
      "sonar/strings-comparison": "error",
      "sonar/super-invocation": "error",
      "sonar/switch-without-default": "off",
      "sonar/table-header": "error",
      "sonar/table-header-reference": "error",
      "sonar/test-check-exception": "error",
      "sonar/todo-tag": "off",
      "sonar/too-many-break-or-continue-in-loop": "error",
      "sonar/unicode-aware-regex": "error",
      "sonar/unnecessary-character-escapes": "error",
      "sonar/unused-import": "error",
      "sonar/unused-named-groups": "error",
      "sonar/unverified-certificate": "error",
      "sonar/unverified-hostname": "error",
      "sonar/updated-const-var": "error",
      "sonar/updated-loop-counter": "error",
      "sonar/use-isnan": "error",
      "sonar/use-type-alias": "error",
      "sonar/values-not-convertible-to-numbers": "error",
      "sonar/variable-name": "error",
      "sonar/void-use": "error",
      "sonar/weak-ssl": "error",
      "sonar/x-powered-by": "error",
      "sonar/xml-parser-xxe": "error",
      "tailwind/classnames-order": "error",
      "tailwind/enforces-negative-arbitrary-values": "error",
      "tailwind/enforces-shorthand": "error",
      "tailwind/migration-from-tailwind-2": "error",
      "tailwind/no-arbitrary-value": "error",
      "tailwind/no-contradicting-classname": "error",
      "tailwind/no-custom-classname": "off",
      "tailwind/no-unnecessary-arbitrary-value": "error",
      "stylistic/array-bracket-newline": ["error", "consistent"],
      "stylistic/array-bracket-spacing": "error",
      "stylistic/array-element-newline": ["error", "consistent"],
      "stylistic/arrow-parens": "error",
      "stylistic/arrow-spacing": "error",
      "stylistic/block-spacing": "off",
      "stylistic/brace-style": "off",
      "stylistic/comma-dangle": "off",
      "stylistic/comma-spacing": "off",
      "stylistic/comma-style": "error",
      "stylistic/computed-property-spacing": "error",
      "stylistic/curly-newline": "error",
      "stylistic/dot-location": ["error", "property"],
      "stylistic/eol-last": "error",
      "stylistic/func-call-spacing": "off",
      "stylistic/function-call-argument-newline": ["error", "consistent"],
      "stylistic/function-call-spacing": "off",
      "stylistic/function-paren-newline": ["error", "consistent"],
      "stylistic/generator-star-spacing": "error",
      "stylistic/implicit-arrow-linebreak": "error",
      "stylistic/indent": "off",
      "stylistic/indent-binary-ops": "error",
      "stylistic/jsx-child-element-spacing": "error",
      "stylistic/jsx-closing-bracket-location": "error",
      "stylistic/jsx-closing-tag-location": "error",
      "stylistic/jsx-curly-brace-presence": "error",
      "stylistic/jsx-curly-newline": "error",
      "stylistic/jsx-curly-spacing": "error",
      "stylistic/jsx-equals-spacing": "error",
      "stylistic/jsx-first-prop-new-line": "error",
      "stylistic/jsx-function-call-newline": "error",
      "stylistic/jsx-indent-props": ["error", 2],
      "stylistic/jsx-max-props-per-line": "error",
      "stylistic/jsx-newline": ["error", { prevent: true }],
      "stylistic/jsx-one-expression-per-line": "error",
      "stylistic/jsx-pascal-case": "error",
      "stylistic/jsx-props-no-multi-spaces": "error",
      "stylistic/jsx-quotes": "error",
      "stylistic/jsx-self-closing-comp": "error",
      "stylistic/jsx-sort-props": "off",
      "stylistic/jsx-tag-spacing": "error",
      "stylistic/jsx-wrap-multilines": [
        "error",
        { declaration: "parens-new-line" },
      ],
      "stylistic/key-spacing": "error",
      "stylistic/keyword-spacing": "off",
      "stylistic/line-comment-position": "off",
      "stylistic/linebreak-style": "error",
      "stylistic/lines-around-comment": "off",
      "stylistic/lines-between-class-members": "off",
      "stylistic/max-len": [
        "error",
        {
          ignoreComments: true,
          ignoreTrailingComments: true,
          ignoreUrls: true,
          ignoreStrings: true,
          ignoreTemplateLiterals: true,
          ignoreRegExpLiterals: true,
        },
      ],
      "stylistic/max-statements-per-line": "error",
      "stylistic/member-delimiter-style": "off",
      "stylistic/multiline-comment-style": "off",
      "stylistic/multiline-ternary": "error",
      "stylistic/new-parens": "error",
      "stylistic/newline-per-chained-call": "error",
      "stylistic/no-confusing-arrow": "error",
      "stylistic/no-extra-parens": "off",
      "stylistic/no-extra-semi": "off",
      "stylistic/no-floating-decimal": "error",
      "stylistic/no-mixed-operators": "error",
      "stylistic/no-mixed-spaces-and-tabs": "error",
      "stylistic/no-multi-spaces": "error",
      "stylistic/no-multiple-empty-lines": [
        "error",
        { max: 1, maxEOF: 1, maxBOF: 0 },
      ],
      "stylistic/no-tabs": "error",
      "stylistic/no-trailing-spaces": "error",
      "stylistic/no-whitespace-before-property": "error",
      "stylistic/nonblock-statement-body-position": "error",
      "stylistic/object-curly-newline": "off",
      "stylistic/object-curly-spacing": "off",
      "stylistic/object-property-newline": "off",
      "stylistic/one-var-declaration-per-line": "error",
      "stylistic/operator-linebreak": "error",
      "stylistic/padded-blocks": ["error", "never"],
      "stylistic/padding-line-between-statements": "off",
      "stylistic/quote-props": "off",
      "stylistic/quotes": "off",
      "stylistic/rest-spread-spacing": "error",
      "stylistic/semi": "off",
      "stylistic/semi-spacing": "error",
      "stylistic/semi-style": "error",
      "stylistic/space-before-blocks": "off",
      "stylistic/space-before-function-paren": "off",
      "stylistic/space-in-parens": "error",
      "stylistic/space-infix-ops": "off",
      "stylistic/space-unary-ops": "error",
      "stylistic/spaced-comment": "error",
      "stylistic/switch-colon-spacing": "error",
      "stylistic/template-curly-spacing": "error",
      "stylistic/template-tag-spacing": "error",
      "stylistic/type-annotation-spacing": "off",
      "stylistic/type-generic-spacing": "error",
      "stylistic/type-named-tuple-spacing": "error",
      "stylistic/wrap-iife": "error",
      "stylistic/wrap-regex": "error",
      "stylistic/yield-star-spacing": "error",
      "stylistic-ts/block-spacing": "error",
      "stylistic-ts/brace-style": "error",
      "stylistic-ts/comma-dangle": [
        "error",
        {
          arrays: "always-multiline",
          objects: "always-multiline",
          imports: "always-multiline",
          exports: "always-multiline",
          functions: "always-multiline",
          enums: "never",
          generics: "always",
          tuples: "never",
        },
      ],
      "stylistic-ts/comma-spacing": "error",
      "stylistic-ts/func-call-spacing": "error",
      "stylistic-ts/function-call-spacing": "error",
      "stylistic-ts/indent": ["error", 2],
      "stylistic-ts/key-spacing": "error",
      "stylistic-ts/keyword-spacing": "error",
      "stylistic-ts/lines-around-comment": "error",
      "stylistic-ts/lines-between-class-members": "error",
      "stylistic-ts/member-delimiter-style": "error",
      "stylistic-ts/no-extra-parens": [
        "error",
        "all",
        { ignoreJSX: "multi-line" },
      ],
      "stylistic-ts/no-extra-semi": "error",
      "stylistic-ts/object-curly-newline": [
        "error",
        { multiline: true, consistent: true },
      ],
      "stylistic-ts/object-curly-spacing": ["error", "always"],
      "stylistic-ts/object-property-newline": "error",
      "stylistic-ts/padding-line-between-statements": "error",
      "stylistic-ts/quote-props": ["error", "as-needed"],
      "stylistic-ts/quotes": "error",
      "stylistic-ts/semi": "error",
      "stylistic-ts/space-before-blocks": "error",
      "stylistic-ts/space-before-function-paren": [
        "error",
        { anonymous: "always", named: "never", asyncArrow: "always" },
      ],
      "stylistic-ts/space-infix-ops": "error",
      "stylistic-ts/type-annotation-spacing": "error",
      "perfectionist/sort-array-includes": "error",
      "perfectionist/sort-classes": "error",
      "perfectionist/sort-enums": "error",
      "perfectionist/sort-exports": "error",
      "perfectionist/sort-imports": [
        "error",
        {
          groups: [
            "type",
            ["builtin", "external"],
            "internal-type",
            "internal",
            ["parent-type", "sibling-type", "index-type"],
            ["parent", "sibling", "index"],
            "object",
            "unknown",
          ],
          newlinesBetween: "always",
        },
      ],
      "perfectionist/sort-interfaces": "error",
      "perfectionist/sort-intersection-types": "error",
      "perfectionist/sort-jsx-props": [
        "error",
        { groups: ["shorthand", "multiline"] },
      ],
      "perfectionist/sort-maps": "error",
      "perfectionist/sort-named-exports": "error",
      "perfectionist/sort-named-imports": "error",
      "perfectionist/sort-object-types": "error",
      "perfectionist/sort-objects": ["error", { partitionByComment: true }],
      "perfectionist/sort-sets": "error",
      "perfectionist/sort-switch-case": [
        "error",
        { order: "asc", type: "alphabetical" },
      ],
      "perfectionist/sort-union-types": "error",
      "perfectionist/sort-variable-declarations": [
        "error",
        { order: "asc", type: "alphabetical" },
      ],
      "@tanstack/query/exhaustive-deps": "error",
      "@tanstack/query/infinite-query-property-order": "error",
      "@tanstack/query/no-rest-destructuring": "error",
      "@tanstack/query/no-unstable-deps": "error",
      "@tanstack/query/stable-query-client": "error",
      "@tanstack/router/create-route-property-order": "error",
      "a11y/alt-text": "error",
      "a11y/anchor-ambiguous-text": "error",
      "a11y/anchor-has-content": "error",
      "a11y/anchor-is-valid": "error",
      "a11y/aria-activedescendant-has-tabindex": "error",
      "a11y/aria-props": "error",
      "a11y/aria-proptypes": "error",
      "a11y/aria-role": "error",
      "a11y/aria-unsupported-elements": "error",
      "a11y/autocomplete-valid": "error",
      "a11y/click-events-have-key-events": "error",
      "a11y/control-has-associated-label": "off",
      "a11y/heading-has-content": "error",
      "a11y/html-has-lang": "error",
      "a11y/iframe-has-title": "error",
      "a11y/img-redundant-alt": "error",
      "a11y/interactive-supports-focus": "error",
      "a11y/label-has-associated-control": "error",
      "a11y/lang": "error",
      "a11y/media-has-caption": "off",
      "a11y/mouse-events-have-key-events": "error",
      "a11y/no-access-key": "error",
      "a11y/no-aria-hidden-on-focusable": "error",
      "a11y/no-autofocus": "error",
      "a11y/no-distracting-elements": "error",
      "a11y/no-interactive-element-to-noninteractive-role": "error",
      "a11y/no-noninteractive-element-interactions": "error",
      "a11y/no-noninteractive-element-to-interactive-role": "error",
      "a11y/no-noninteractive-tabindex": "error",
      "a11y/no-redundant-roles": "error",
      "a11y/no-static-element-interactions": "error",
      "a11y/prefer-tag-over-role": "error",
      "a11y/role-has-required-aria-props": "error",
      "a11y/role-supports-aria-props": "error",
      "a11y/scope": "error",
      "a11y/tabindex-no-positive": "error",
      "array-bracket-newline": "off",
      "array-bracket-spacing": "off",
      "array-element-newline": "off",
      "arrow-parens": "off",
      "arrow-spacing": "off",
      "block-spacing": "off",
      "brace-style": "off",
      "callback-return": "off",
      "comma-dangle": "off",
      "comma-spacing": "off",
      "comma-style": "off",
      "computed-property-spacing": "off",
      "dot-location": "off",
      "eol-last": "off",
      "func-call-spacing": "off",
      "function-call-argument-newline": "off",
      "function-paren-newline": "off",
      "generator-star-spacing": "off",
      "global-require": "off",
      "handle-callback-err": "off",
      "id-blacklist": "off",
      "implicit-arrow-linebreak": "off",
      indent: "off",
      "indent-legacy": "off",
      "jsx-quotes": "off",
      "key-spacing": "off",
      "keyword-spacing": "off",
      "line-comment-position": "off",
      "linebreak-style": "off",
      "lines-around-comment": "off",
      "lines-around-directive": "off",
      "lines-between-class-members": "off",
      "max-len": "off",
      "max-statements-per-line": "off",
      "multiline-comment-style": "off",
      "multiline-ternary": "off",
      "new-parens": "off",
      "newline-after-var": "off",
      "newline-before-return": "off",
      "newline-per-chained-call": "off",
      "no-buffer-constructor": "off",
      "no-catch-shadow": "off",
      "no-confusing-arrow": "off",
      "no-extra-parens": "off",
      "no-extra-semi": "off",
      "no-floating-decimal": "off",
      "no-mixed-operators": "off",
      "no-mixed-requires": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-multi-spaces": "off",
      "no-multiple-empty-lines": "off",
      "no-native-reassign": "off",
      "no-negated-in-lhs": "off",
      "no-new-object": "off",
      "no-new-require": "off",
      "no-new-symbol": "off",
      "no-path-concat": "off",
      "no-process-env": "off",
      "no-process-exit": "off",
      "no-restricted-modules": "off",
      "no-return-await": "off",
      "no-spaced-func": "off",
      "no-sync": "off",
      "no-tabs": "off",
      "no-trailing-spaces": "off",
      "no-whitespace-before-property": "off",
      "nonblock-statement-body-position": "off",
      "object-curly-newline": "off",
      "object-curly-spacing": "off",
      "object-property-newline": "off",
      "one-var-declaration-per-line": "off",
      "operator-linebreak": "off",
      "padded-blocks": "off",
      "padding-line-between-statements": "off",
      "prefer-reflect": "off",
      "quote-props": "off",
      quotes: "off",
      "rest-spread-spacing": "off",
      semi: "off",
      "semi-spacing": "off",
      "semi-style": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "spaced-comment": "off",
      "switch-colon-spacing": "off",
      "template-curly-spacing": "off",
      "template-tag-spacing": "off",
      "wrap-iife": "off",
      "wrap-regex": "off",
      "yield-star-spacing": "off",
    },
  },
  {
    files: ["**/*.md"],
    plugins: {
      markdown: markdown,
    },
    rules: {
      "markdown/fenced-code-language": "error",
      "markdown/heading-increment": "error",
      "markdown/no-duplicate-headings": "error",
      "markdown/no-empty-links": "error",
      "markdown/no-html": "error",
      "markdown/no-invalid-label-refs": "error",
      "markdown/no-missing-label-refs": "error",
    },
  },
  {
    files: ["**/*.json"],
    language: "json/json",
    plugins: {
      json: json,
    },
    rules: {
      "json/no-duplicate-keys": "error",
      "json/no-empty-keys": "error",
    },
  },
  {
    files: ["**/*.jsonc"],
    language: "json/jsonc",
    plugins: {
      json: json,
    },
    rules: {
      "json/no-duplicate-keys": "error",
      "json/no-empty-keys": "error",
    },
  },
  {
    files: ["**/*.json5"],
    language: "json/json5",
    plugins: {
      json: json,
    },
    rules: {
      "json/no-duplicate-keys": "error",
      "json/no-empty-keys": "error",
    },
  },
);
